uploads = []
generated = []

[[outputs]]
id = "VsveSrplzLSBdocqTJrPD"
uri = "file://artifacts/markaz-rabithah/public/opengraph.jpg"
type = "image"
title = "OpenGraph preview"

[[outputs]]
id = "siabfpGsecVDrrU0gjk8X"
uri = "file://artifacts/markaz-rabithah/public/favicon-192.png"
type = "image"
title = "Favicon (192px)"
